from app.agents.base_agent import BaseAgent
from app.services.gemini_service import GeminiService


class ConversationAgent(BaseAgent):
    """
    Default conversational agent for D.AI.SY.

    Delegates conversational requests to the GeminiService.
    """

    def __init__(self, gemini_service: GeminiService):
        self._gemini_service = gemini_service

    @property
    def name(self) -> str:
        return "Conversation Agent"

    async def run(self, request):
        """
        Process a conversational request.

        Args:
            request: User message.

        Returns:
            Response generated by GeminiService.
        """
        return self._gemini_service.generate(request)